#!/bin/sh

# path to the web server root directory
ROOT=$( dirname "$0" )"/../.."

. "$ROOT/web.cfg"

. "$ROOT/scripts/util.sh"

read -r POST_QUERY_STRING

validate_query_string "$QUERY_STRING" && validate_query_string "$POST_QUERY_STRING" || invalid_request

DEVICE=$( query_string_get_value "$POST_QUERY_STRING" "device" )
DESCRIPTION=$( query_string_get_value "$POST_QUERY_STRING" "description" )
CONTINUE=$( query_string_get_value "$QUERY_STRING" "continue" )

init_session

if [ -n "$DEVICE" ]
then
	check_name "$DEVICE" || show_error "Invalid device name!"

	DESCRIPTION_ENCODED=$( printf "%s" "$DESCRIPTION" | base64 -w 0 )

	DEVICE_INFO="{\"name\":\"$DEVICE\",\"description\":\"$DESCRIPTION_ENCODED\"}"

	if ! send_request "{\"session\":\"$SESSION\",\"device\":$DEVICE_INFO}" "$MASTER_SERVER_URL/api/device/create"
	then
		[ "$REQUEST_STATUS" = "invalid_session"  ] && login_redirect
		[ "$REQUEST_STATUS" = "invalid_name"     ] && show_error "Invalid device name!"
		[ "$REQUEST_STATUS" = "device_exists"    ] && show_error "Device '$DEVICE' already exists!"
		[ "$REQUEST_STATUS" = "max_device_count" ] && show_error "You have reached the maximum device count!"

		server_error
	fi

	[ -z "$CONTINUE" ] && CONTINUE="main"

	http_redirect "$CONTINUE"
fi

create_page_content()
{
	echo "<!DOCTYPE html>"
	echo "<html lang=\"en\">"
	echo "<head>"
	echo "  <meta charset=\"UTF-8\">"
	echo "  <title>WireGuard VPN Manager</title>"
	echo "</head>"
	echo "<body>"
	echo "  <h2>Add new device</h2>"
	echo "  <form action=\"$REQUEST_URI\" method=\"post\">"
	echo "    Name:<br>"
	echo "    <input type=\"text\" name=\"device\"><br>"
	echo "    Description:<br>"
	echo "    <input type=\"text\" name=\"description\"><br>"
	echo "    <br>"
	echo "    <input type=\"submit\" value=\"Add device\">"
	echo "  </form>"
	echo "</body>"
	echo "</html>"
}

show_page
