#!/bin/sh

# path to the web server root directory
ROOT=$( dirname "$0" )"/../.."

. "$ROOT/web.cfg"

. "$ROOT/scripts/util.sh"

read -r POST_QUERY_STRING

validate_query_string "$QUERY_STRING" && validate_query_string "$POST_QUERY_STRING" || invalid_request

USERNAME=$( query_string_get_value "$POST_QUERY_STRING" "username" )
PASSWORD=$( query_string_get_value "$POST_QUERY_STRING" "password" )
CONTINUE=$( query_string_get_value "$QUERY_STRING" "continue" )

if [ -n "$USERNAME" ] && [ -n "$PASSWORD" ]
then
	check_name "$USERNAME" || show_error "Invalid username!"

	PASSWORD_ENCRYPTED=$( encrypt_password "$PASSWORD" )

	if ! send_request "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD_ENCRYPTED\"}" "$MASTER_SERVER_URL/api/user/login"
	then
		[ "$REQUEST_STATUS" = "fail" ] && show_error "Incorrect username or password!"

		server_error
	fi

	[ -z "$CONTINUE" ] && CONTINUE="main"

	http_redirect "$CONTINUE"
fi

create_page_content()
{
	echo "<!DOCTYPE html>"
	echo "<html lang=\"en\">"
	echo "<head>"
	echo "  <meta charset=\"UTF-8\">"
	echo "  <title>WireGuard VPN Manager</title>"
	echo "</head>"
	echo "<body>"
	echo "  <h2>Login</h2>"
	echo "  <form action=\"$REQUEST_URI\" method=\"post\">"
	echo "    Username:<br>"
	echo "    <input type=\"text\" name=\"username\"><br>"
	echo "    Password:<br>"
	echo "    <input type=\"password\" name=\"password\"><br>"
	echo "    <br>"
	echo "    <input type=\"submit\" value=\"Login\">"
	echo "  </form>"
	echo "</body>"
	echo "</html>"
}

show_page
