#!/bin/sh

# path to the master server root directory
ROOT=$( dirname "$0" )"/../../../.."

. "$ROOT/scripts/util.sh"

log_result()
{
	log_info "/api/gate/started: $1 $REMOTE_ADDR:$REMOTE_PORT"
}

read -r REQUEST

GATE_KEY=$( echo "$REQUEST" | jq -r '.key // empty' )

if [ -z "$GATE_KEY" ]
then
	log_result "Invalid request"
	response_invalid_request
	exit 1
fi

# acquire database lock and process the request
if ! flock "$ROOT/db" "$ROOT/scripts/api-gate-started.sh" "$GATE_KEY"
then
	log_result "Failure"
	exit 1
fi

log_result "Success"
